#!/usr/bin/env bash
# another trivial example of while lop and if statement

counter=0

while [[ counter -le 10 ]]
do
    if [[ $counter -eq 4 ]] || [[ $counter -eq 8 ]]
    then 
        echo "bad luck"
    else 
        echo "Best School"
    fi 

    ((counter++))
done 