#!/usr/bin/env bash
# yet andother tirival while loop with if statements and shit 

counter=0

while [[ counter -le 20 ]]; do
    case $counter in
        17)
        printf "bad luck from Italy\n"
        ;;
        9)
        printf "bad luck from Japan\n"
        ;;
        4)
        printf "bad luck from China\n"
        ;;
        *)
        ;;
    esac

    printf "%s\n" "$counter"
    
    ((counter++))
done 