#!/usr/bin/env bash
# A script to do their silly littel clock thing,,,

hour=0
min=1

while [[ hour -le 12 ]]; do

    printf "Hour: %s\n" "$hour"

    while [[ min -lt 60 ]]; do
        printf "%s\n" "$min"
        ((min++))
    done 

    min=1
    ((hour++))
done
