#!/usr/bin/env bash
# A scrip[t that checks if another file exists and is not empty

if [ -r school ]; then

    echo "school file exists"

    if [ ! -d school ]; then 
        echo "school is a regular file"
    fi 

    #See if the file has a length greater than zero 
    if [[ -s school ]]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi 
else 
    echo "school file does not exist"
fi 
