#!/usr/bin/env bash
# This script installs and configures HAproxy load balancer
# HAproxy will send traffic to 5533-web-01 and 5533-web-02
# Requests will be distributed using round robin algorithm

config_frontend="\nfrontend main\n\tbind *:80\n\tmode http\n\tdefault_backend web_servers\n"
config_backend="\nbackend web_servers\n\tbalance roundrobin\n\toption forwardfor\n\tserver 5533-web-01 15.236.18.116:80 check\n\tserver 5533-web-02 52.47.204.49:80 check\n"

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo ENABLED=1 | sudo tee -a /etc/default/haproxy
echo -e "$config_frontend""$config_backend" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start